repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml
      - id: check-merge-conflict
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v13.0.0
    hooks:
      - id: clang-format
        files: src/.*\.(cxx|hxx)$
        exclude: ^deps/
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0
    hooks:
      - id: autopep8
        exclude: ^(deps/|src/)
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: |
          (?x)^(
              deps/|
              src/|
              protostellar/proto/|
              simple_acouchbase.py|
              simple_couchbase.py|
              simple_txcouchbase.py|
              couchbase_kv_tests.py|
              examples/
          )
        args:
          [
            --max-line-length=120,
            --max-complexity=10
          ]
  - repo: https://github.com/PyCQA/isort
    rev: 5.11.5
    hooks:
      - id: isort
        exclude: |
          (?x)^(
              deps/|
              src/|
              protostellar/proto/|
              examples/txcouchbase/
          )
        args:
          [
            "--multi-line 1",
            "--force-grid-wrap 3",
            "--use-parentheses True",
            "--ensure-newline-before-comments True",
            "--line-length 120",
            "--order-by-type True"
          ]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.2
    hooks:
      - id: bandit
        exclude: |
          (?x)^(
              deps/|
              src/|
              protostellar/proto/|
              acouchbase/tests/|
              txcouchbase/tests/|
              couchbase/tests/|
              protostellar/tests/|
              tests/mock_server.py|
              tests/environments/|
              simple_acouchbase.py|
              simple_couchbase.py|
              simple_txcouchbase.py|
              couchbase_kv_tests.py|
              couchbase_version.py
          )
        args:
          [
              --quiet
          ]
