# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from new_couchbase.protostellar.proto.couchbase.internal.hooks.v1 import hooks_pb2 as couchbase_dot_internal_dot_hooks_dot_v1_dot_hooks__pb2


class HooksServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateHooksContext = channel.unary_unary(
                '/couchbase.internal.hooks.v1.HooksService/CreateHooksContext',
                request_serializer=couchbase_dot_internal_dot_hooks_dot_v1_dot_hooks__pb2.CreateHooksContextRequest.SerializeToString,
                response_deserializer=couchbase_dot_internal_dot_hooks_dot_v1_dot_hooks__pb2.CreateHooksContextResponse.FromString,
                )
        self.DestroyHooksContext = channel.unary_unary(
                '/couchbase.internal.hooks.v1.HooksService/DestroyHooksContext',
                request_serializer=couchbase_dot_internal_dot_hooks_dot_v1_dot_hooks__pb2.DestroyHooksContextRequest.SerializeToString,
                response_deserializer=couchbase_dot_internal_dot_hooks_dot_v1_dot_hooks__pb2.DestroyHooksContextResponse.FromString,
                )
        self.AddHooks = channel.unary_unary(
                '/couchbase.internal.hooks.v1.HooksService/AddHooks',
                request_serializer=couchbase_dot_internal_dot_hooks_dot_v1_dot_hooks__pb2.AddHooksRequest.SerializeToString,
                response_deserializer=couchbase_dot_internal_dot_hooks_dot_v1_dot_hooks__pb2.AddHooksResponse.FromString,
                )
        self.WatchBarrier = channel.unary_stream(
                '/couchbase.internal.hooks.v1.HooksService/WatchBarrier',
                request_serializer=couchbase_dot_internal_dot_hooks_dot_v1_dot_hooks__pb2.WatchBarrierRequest.SerializeToString,
                response_deserializer=couchbase_dot_internal_dot_hooks_dot_v1_dot_hooks__pb2.WatchBarrierResponse.FromString,
                )
        self.SignalBarrier = channel.unary_unary(
                '/couchbase.internal.hooks.v1.HooksService/SignalBarrier',
                request_serializer=couchbase_dot_internal_dot_hooks_dot_v1_dot_hooks__pb2.SignalBarrierRequest.SerializeToString,
                response_deserializer=couchbase_dot_internal_dot_hooks_dot_v1_dot_hooks__pb2.SignalBarrierResponse.FromString,
                )


class HooksServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateHooksContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroyHooksContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddHooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchBarrier(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignalBarrier(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HooksServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateHooksContext': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateHooksContext,
                    request_deserializer=couchbase_dot_internal_dot_hooks_dot_v1_dot_hooks__pb2.CreateHooksContextRequest.FromString,
                    response_serializer=couchbase_dot_internal_dot_hooks_dot_v1_dot_hooks__pb2.CreateHooksContextResponse.SerializeToString,
            ),
            'DestroyHooksContext': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroyHooksContext,
                    request_deserializer=couchbase_dot_internal_dot_hooks_dot_v1_dot_hooks__pb2.DestroyHooksContextRequest.FromString,
                    response_serializer=couchbase_dot_internal_dot_hooks_dot_v1_dot_hooks__pb2.DestroyHooksContextResponse.SerializeToString,
            ),
            'AddHooks': grpc.unary_unary_rpc_method_handler(
                    servicer.AddHooks,
                    request_deserializer=couchbase_dot_internal_dot_hooks_dot_v1_dot_hooks__pb2.AddHooksRequest.FromString,
                    response_serializer=couchbase_dot_internal_dot_hooks_dot_v1_dot_hooks__pb2.AddHooksResponse.SerializeToString,
            ),
            'WatchBarrier': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchBarrier,
                    request_deserializer=couchbase_dot_internal_dot_hooks_dot_v1_dot_hooks__pb2.WatchBarrierRequest.FromString,
                    response_serializer=couchbase_dot_internal_dot_hooks_dot_v1_dot_hooks__pb2.WatchBarrierResponse.SerializeToString,
            ),
            'SignalBarrier': grpc.unary_unary_rpc_method_handler(
                    servicer.SignalBarrier,
                    request_deserializer=couchbase_dot_internal_dot_hooks_dot_v1_dot_hooks__pb2.SignalBarrierRequest.FromString,
                    response_serializer=couchbase_dot_internal_dot_hooks_dot_v1_dot_hooks__pb2.SignalBarrierResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'couchbase.internal.hooks.v1.HooksService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HooksService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateHooksContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/couchbase.internal.hooks.v1.HooksService/CreateHooksContext',
            couchbase_dot_internal_dot_hooks_dot_v1_dot_hooks__pb2.CreateHooksContextRequest.SerializeToString,
            couchbase_dot_internal_dot_hooks_dot_v1_dot_hooks__pb2.CreateHooksContextResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DestroyHooksContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/couchbase.internal.hooks.v1.HooksService/DestroyHooksContext',
            couchbase_dot_internal_dot_hooks_dot_v1_dot_hooks__pb2.DestroyHooksContextRequest.SerializeToString,
            couchbase_dot_internal_dot_hooks_dot_v1_dot_hooks__pb2.DestroyHooksContextResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddHooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/couchbase.internal.hooks.v1.HooksService/AddHooks',
            couchbase_dot_internal_dot_hooks_dot_v1_dot_hooks__pb2.AddHooksRequest.SerializeToString,
            couchbase_dot_internal_dot_hooks_dot_v1_dot_hooks__pb2.AddHooksResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WatchBarrier(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/couchbase.internal.hooks.v1.HooksService/WatchBarrier',
            couchbase_dot_internal_dot_hooks_dot_v1_dot_hooks__pb2.WatchBarrierRequest.SerializeToString,
            couchbase_dot_internal_dot_hooks_dot_v1_dot_hooks__pb2.WatchBarrierResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SignalBarrier(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/couchbase.internal.hooks.v1.HooksService/SignalBarrier',
            couchbase_dot_internal_dot_hooks_dot_v1_dot_hooks__pb2.SignalBarrierRequest.SerializeToString,
            couchbase_dot_internal_dot_hooks_dot_v1_dot_hooks__pb2.SignalBarrierResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
