# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: couchbase/internal/health.v1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"couchbase/internal/health.v1.proto\x12\x13\x63ouchbase.health.v1\"%\n\x12HealthCheckRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"\xae\x01\n\x13HealthCheckResponse\x12\x46\n\x06status\x18\x01 \x01(\x0e\x32\x36.couchbase.health.v1.HealthCheckResponse.ServingStatus\"O\n\rServingStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SERVING\x10\x01\x12\x0f\n\x0bNOT_SERVING\x10\x02\x12\x13\n\x0fSERVICE_UNKNOWN\x10\x03\x32\xc2\x01\n\x06Health\x12Z\n\x05\x43heck\x12\'.couchbase.health.v1.HealthCheckRequest\x1a(.couchbase.health.v1.HealthCheckResponse\x12\\\n\x05Watch\x12\'.couchbase.health.v1.HealthCheckRequest\x1a(.couchbase.health.v1.HealthCheckResponse0\x01\x42\xeb\x01\n4com.couchbase.client.protostellar.internal.health.v1P\x01Z@github.com/couchbase/goprotostellar/genproto/health_v1;health_v1\xca\x02\x33\x43ouchbase\\Protostellar\\Generated\\Internal\\Health\\V1\xea\x02\x38\x43ouchbase::Protostellar::Generated::Internal::Health::V1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'couchbase.internal.health.v1_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n4com.couchbase.client.protostellar.internal.health.v1P\001Z@github.com/couchbase/goprotostellar/genproto/health_v1;health_v1\312\0023Couchbase\\Protostellar\\Generated\\Internal\\Health\\V1\352\0028Couchbase::Protostellar::Generated::Internal::Health::V1'
  _HEALTHCHECKREQUEST._serialized_start=59
  _HEALTHCHECKREQUEST._serialized_end=96
  _HEALTHCHECKRESPONSE._serialized_start=99
  _HEALTHCHECKRESPONSE._serialized_end=273
  _HEALTHCHECKRESPONSE_SERVINGSTATUS._serialized_start=194
  _HEALTHCHECKRESPONSE_SERVINGSTATUS._serialized_end=273
  _HEALTH._serialized_start=276
  _HEALTH._serialized_end=470
# @@protoc_insertion_point(module_scope)
