# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from new_couchbase.impl.protostellar.proto.couchbase.analytics import v1_pb2 as couchbase_dot_analytics_dot_v1__pb2


class AnalyticsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyticsQuery = channel.unary_stream(
                '/couchbase.analytics.v1.Analytics/AnalyticsQuery',
                request_serializer=couchbase_dot_analytics_dot_v1__pb2.AnalyticsQueryRequest.SerializeToString,
                response_deserializer=couchbase_dot_analytics_dot_v1__pb2.AnalyticsQueryResponse.FromString,
                )


class AnalyticsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AnalyticsQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalyticsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyticsQuery': grpc.unary_stream_rpc_method_handler(
                    servicer.AnalyticsQuery,
                    request_deserializer=couchbase_dot_analytics_dot_v1__pb2.AnalyticsQueryRequest.FromString,
                    response_serializer=couchbase_dot_analytics_dot_v1__pb2.AnalyticsQueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'couchbase.analytics.v1.Analytics', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Analytics(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyticsQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/couchbase.analytics.v1.Analytics/AnalyticsQuery',
            couchbase_dot_analytics_dot_v1__pb2.AnalyticsQueryRequest.SerializeToString,
            couchbase_dot_analytics_dot_v1__pb2.AnalyticsQueryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
