# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from new_couchbase.impl.protostellar.proto.couchbase.search import v1_pb2 as couchbase_dot_search_dot_v1__pb2


class SearchStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchQuery = channel.unary_stream(
                '/couchbase.search.v1.Search/SearchQuery',
                request_serializer=couchbase_dot_search_dot_v1__pb2.SearchQueryRequest.SerializeToString,
                response_deserializer=couchbase_dot_search_dot_v1__pb2.SearchQueryResponse.FromString,
                )


class SearchServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SearchQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SearchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchQuery': grpc.unary_stream_rpc_method_handler(
                    servicer.SearchQuery,
                    request_deserializer=couchbase_dot_search_dot_v1__pb2.SearchQueryRequest.FromString,
                    response_serializer=couchbase_dot_search_dot_v1__pb2.SearchQueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'couchbase.search.v1.Search', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Search(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SearchQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/couchbase.search.v1.Search/SearchQuery',
            couchbase_dot_search_dot_v1__pb2.SearchQueryRequest.SerializeToString,
            couchbase_dot_search_dot_v1__pb2.SearchQueryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
