# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from new_couchbase.impl.protostellar.proto.couchbase.view import v1_pb2 as couchbase_dot_view_dot_v1__pb2


class ViewStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ViewQuery = channel.unary_stream(
                '/couchbase.view.v1.View/ViewQuery',
                request_serializer=couchbase_dot_view_dot_v1__pb2.ViewQueryRequest.SerializeToString,
                response_deserializer=couchbase_dot_view_dot_v1__pb2.ViewQueryResponse.FromString,
                )


class ViewServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ViewQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ViewServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ViewQuery': grpc.unary_stream_rpc_method_handler(
                    servicer.ViewQuery,
                    request_deserializer=couchbase_dot_view_dot_v1__pb2.ViewQueryRequest.FromString,
                    response_serializer=couchbase_dot_view_dot_v1__pb2.ViewQueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'couchbase.view.v1.View', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class View(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ViewQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/couchbase.view.v1.View/ViewQuery',
            couchbase_dot_view_dot_v1__pb2.ViewQueryRequest.SerializeToString,
            couchbase_dot_view_dot_v1__pb2.ViewQueryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
