# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from new_couchbase.protostellar.proto.couchbase.routing import v1_pb2 as couchbase_dot_routing_dot_v1__pb2


class RoutingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WatchRouting = channel.unary_stream(
                '/couchbase.routing.v1.Routing/WatchRouting',
                request_serializer=couchbase_dot_routing_dot_v1__pb2.WatchRoutingRequest.SerializeToString,
                response_deserializer=couchbase_dot_routing_dot_v1__pb2.WatchRoutingResponse.FromString,
                )


class RoutingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def WatchRouting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoutingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WatchRouting': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchRouting,
                    request_deserializer=couchbase_dot_routing_dot_v1__pb2.WatchRoutingRequest.FromString,
                    response_serializer=couchbase_dot_routing_dot_v1__pb2.WatchRoutingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'couchbase.routing.v1.Routing', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Routing(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def WatchRouting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/couchbase.routing.v1.Routing/WatchRouting',
            couchbase_dot_routing_dot_v1__pb2.WatchRoutingRequest.SerializeToString,
            couchbase_dot_routing_dot_v1__pb2.WatchRoutingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
