"""

    PYCBC_FMT_LEGACY_JSON = 0x00,
    PYCBC_FMT_LEGACY_PICKLE = 0x01,
    PYCBC_FMT_LEGACY_BYTES = 0x02,
    PYCBC_FMT_LEGACY_UTF8 = 0x04,
    PYCBC_FMT_LEGACY_MASK = 0x07,

    PYCBC_FMT_COMMON_PICKLE = (0x01U << 24),
    PYCBC_FMT_COMMON_JSON = (0x02U << 24),
    PYCBC_FMT_COMMON_BYTES = (0x03U << 24),
    PYCBC_FMT_COMMON_UTF8 = (0x04U << 24),
    PYCBC_FMT_COMMON_MASK = (0xFFU << 24),

    PYCBC_FMT_JSON = PYCBC_FMT_LEGACY_JSON | PYCBC_FMT_COMMON_JSON,
    PYCBC_FMT_PICKLE = PYCBC_FMT_LEGACY_PICKLE | PYCBC_FMT_COMMON_PICKLE,
    PYCBC_FMT_BYTES = PYCBC_FMT_LEGACY_BYTES | PYCBC_FMT_COMMON_BYTES,
    PYCBC_FMT_UTF8 = PYCBC_FMT_LEGACY_UTF8 | PYCBC_FMT_COMMON_UTF8

"""

# 'private' common flags format
_NF_JSON = 0x00
_NF_PICKLE = 0x01
_NF_BYTES = 0x02
_NF_UTF8 = 0x04
_NF_MASK = 0xFF

# 'private' common flags format
_CF_PICKLE = 0x01 << 24
_CF_JSON = 0x02 << 24
_CF_BYTES = 0x03 << 24
_CF_UTF8 = 0x04 << 24
_CF_MASK = 0xFF << 24


# public constants
FMT_BYTES = _NF_BYTES | _CF_BYTES
FMT_COMMON_MASK = _CF_MASK
FMT_JSON = _NF_JSON | _CF_JSON
FMT_LEGACY_MASK = _NF_MASK
FMT_PICKLE = _NF_PICKLE | _CF_PICKLE
FMT_UTF8 = _NF_UTF8 | _CF_UTF8
