# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from new_couchbase.protostellar.proto.couchbase.admin.collection import v1_pb2 as couchbase_dot_admin_dot_collection_dot_v1__pb2


class CollectionAdminStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListCollections = channel.unary_unary(
                '/couchbase.admin.collection.v1.CollectionAdmin/ListCollections',
                request_serializer=couchbase_dot_admin_dot_collection_dot_v1__pb2.ListCollectionsRequest.SerializeToString,
                response_deserializer=couchbase_dot_admin_dot_collection_dot_v1__pb2.ListCollectionsResponse.FromString,
                )
        self.CreateScope = channel.unary_unary(
                '/couchbase.admin.collection.v1.CollectionAdmin/CreateScope',
                request_serializer=couchbase_dot_admin_dot_collection_dot_v1__pb2.CreateScopeRequest.SerializeToString,
                response_deserializer=couchbase_dot_admin_dot_collection_dot_v1__pb2.CreateScopeResponse.FromString,
                )
        self.DeleteScope = channel.unary_unary(
                '/couchbase.admin.collection.v1.CollectionAdmin/DeleteScope',
                request_serializer=couchbase_dot_admin_dot_collection_dot_v1__pb2.DeleteScopeRequest.SerializeToString,
                response_deserializer=couchbase_dot_admin_dot_collection_dot_v1__pb2.DeleteScopeResponse.FromString,
                )
        self.CreateCollection = channel.unary_unary(
                '/couchbase.admin.collection.v1.CollectionAdmin/CreateCollection',
                request_serializer=couchbase_dot_admin_dot_collection_dot_v1__pb2.CreateCollectionRequest.SerializeToString,
                response_deserializer=couchbase_dot_admin_dot_collection_dot_v1__pb2.CreateCollectionResponse.FromString,
                )
        self.DeleteCollection = channel.unary_unary(
                '/couchbase.admin.collection.v1.CollectionAdmin/DeleteCollection',
                request_serializer=couchbase_dot_admin_dot_collection_dot_v1__pb2.DeleteCollectionRequest.SerializeToString,
                response_deserializer=couchbase_dot_admin_dot_collection_dot_v1__pb2.DeleteCollectionResponse.FromString,
                )


class CollectionAdminServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListCollections(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateScope(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteScope(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CollectionAdminServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListCollections': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCollections,
                    request_deserializer=couchbase_dot_admin_dot_collection_dot_v1__pb2.ListCollectionsRequest.FromString,
                    response_serializer=couchbase_dot_admin_dot_collection_dot_v1__pb2.ListCollectionsResponse.SerializeToString,
            ),
            'CreateScope': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateScope,
                    request_deserializer=couchbase_dot_admin_dot_collection_dot_v1__pb2.CreateScopeRequest.FromString,
                    response_serializer=couchbase_dot_admin_dot_collection_dot_v1__pb2.CreateScopeResponse.SerializeToString,
            ),
            'DeleteScope': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteScope,
                    request_deserializer=couchbase_dot_admin_dot_collection_dot_v1__pb2.DeleteScopeRequest.FromString,
                    response_serializer=couchbase_dot_admin_dot_collection_dot_v1__pb2.DeleteScopeResponse.SerializeToString,
            ),
            'CreateCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCollection,
                    request_deserializer=couchbase_dot_admin_dot_collection_dot_v1__pb2.CreateCollectionRequest.FromString,
                    response_serializer=couchbase_dot_admin_dot_collection_dot_v1__pb2.CreateCollectionResponse.SerializeToString,
            ),
            'DeleteCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCollection,
                    request_deserializer=couchbase_dot_admin_dot_collection_dot_v1__pb2.DeleteCollectionRequest.FromString,
                    response_serializer=couchbase_dot_admin_dot_collection_dot_v1__pb2.DeleteCollectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'couchbase.admin.collection.v1.CollectionAdmin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CollectionAdmin(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListCollections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/couchbase.admin.collection.v1.CollectionAdmin/ListCollections',
            couchbase_dot_admin_dot_collection_dot_v1__pb2.ListCollectionsRequest.SerializeToString,
            couchbase_dot_admin_dot_collection_dot_v1__pb2.ListCollectionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateScope(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/couchbase.admin.collection.v1.CollectionAdmin/CreateScope',
            couchbase_dot_admin_dot_collection_dot_v1__pb2.CreateScopeRequest.SerializeToString,
            couchbase_dot_admin_dot_collection_dot_v1__pb2.CreateScopeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteScope(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/couchbase.admin.collection.v1.CollectionAdmin/DeleteScope',
            couchbase_dot_admin_dot_collection_dot_v1__pb2.DeleteScopeRequest.SerializeToString,
            couchbase_dot_admin_dot_collection_dot_v1__pb2.DeleteScopeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/couchbase.admin.collection.v1.CollectionAdmin/CreateCollection',
            couchbase_dot_admin_dot_collection_dot_v1__pb2.CreateCollectionRequest.SerializeToString,
            couchbase_dot_admin_dot_collection_dot_v1__pb2.CreateCollectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/couchbase.admin.collection.v1.CollectionAdmin/DeleteCollection',
            couchbase_dot_admin_dot_collection_dot_v1__pb2.DeleteCollectionRequest.SerializeToString,
            couchbase_dot_admin_dot_collection_dot_v1__pb2.DeleteCollectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
